### ISSUE TITLE
improve authentication

### ISSUE THREAD

**Issue by chripo** [studio-b12/gowebdav#15]
fix #14 in commit b45378c changed the behaviour of the `req()` method. the auth checks were moved from `Connect()` to `req()`.
 
how to improve the code to keep the modification inside the client, because it's a client improvement and to keep the request as small as possible.

suggestions and discussion are welcome!

**Comment by chuckwagoncomputing** [comment]
Good points. We'd have to add a check on each of [ReadDir, Stat, et. al.]. Maybe add a function to do the checking, initialize auth, and call the calling function again, passed as a parameter? With this approach there will be more code that unnecessarily runs twice.

**Comment by MrVine** [comment]
If I correctly understand you, @chuckwagoncomputing , you suggest to add a check on each of [ReadDir, Stat, etc] functions?
Instead, I want to suggest to add a function which will do _the checking and initialize auth_ directly to `req()` function. 

What do you think about it?

**Comment by chuckwagoncomputing** [comment]
From the standpoint of "seperation of concerns", that's essentially what I've done. @chripo's suggestion is that the checking should be the job of the Client part of the library, rather than the Requests part.

**Comment by MrVine** [comment]
Thanks for explanation. Unfortunately I have no ideas how we can deal with this.

**Comment by MrVine** [comment]
@chripo , I think to remove `TeeReader` from `req()` method, we should perform auth checking in separate method. For example, I propose to return `c.Connect()` method, but use PROPFIND instead of OPTIONS.

**Comment by chripo** [comment]
From my point of view, sending the body twice is a total waste of performance and time.
Adding a strategy for auth would cleanup the code. I worked already on it, but unfinished,i'll share my code soon.

I think there is a way to send the first 6request without a body, need time for a deeper look into the specs / rfcs.

**Comment by chuckwagoncomputing** [comment]
I haven't actually read the RFCs, but I know some clients do not send the body the first time. SabreDAV has a bug and won't authenticate with an empty body. The maintainer refused to fix it because he claimed it was non-standard to send the first packet without a body. It does have a workaround though.

**Comment by chuckwagoncomputing** [comment]
@chripo, have you got anywhere with this?

**Comment by pdf** [comment]
@MrVine wrote:
> We must not support Basic authentication method (RFC4918)

That makes no sense for a client library.  The RFC states that servers must not present a Basic challenge, _unless_ they're served over a secure connection (ie - TLS).  I'd suggest that Basic auth is very widely implemented, as generally connections will be TLS encrypted.  I'd be very concerned about any authentication over insecure channels, as leaking bearer tokens or other form of auth is frequently just as bad as leaking a username/password. In fact, Basic auth _must_ be supported, for servers that only support it, and it's likely the only globally supported mechanism.

> I propose to ... use the second approach from Appendix E inside it

I see very little value in complicating the auth mechanism in this direction, based on the above, and also based on the caveats listed in the RFC.
