### ISSUE TITLE
Apache HTTPS Server does not return `Dav` or `DAV` header on `OPTIONS` request

### ISSUE THREAD

**Issue by MrVine** [studio-b12/gowebdav#16]
Here is the current version of `Connect` function:
```
// Connect connects to our dav server
func (c *Client) Connect() error {
	rs, err := c.options("/")
	if err != nil {
		return err
	}

	err = rs.Body.Close()
	if err != nil {
		return err
	}

	if rs.StatusCode != 200 || (rs.Header.Get("Dav") == "" && rs.Header.Get("DAV") == "") {
		return newPathError("Connect", c.root, rs.StatusCode)
	}

	return nil
}
```

but `Apache HTTPS Server` does not return `Dav` or `DAV` header, so application returns following message on any request:
```
Failed to connect due to: Connect https://mywebdav.me/: 200
```

Is it bug in library, or wrong settings of `Apache HTTPS Server`?

**Comment by chripo** [comment]
a WebDAV server should send a `DAV` and `Allow` HEADER for an OPTIONS request.
please submit your output:
`curl -u '$USER:$PASSWORD' -i -X OPTIONS https://$YOUR_DAV_SERVER`
thanks.

i'm consider to drop the Connect / options request.

**Comment by MrVine** [comment]
Apache HTTPS request:
```
curl -u '$USER:$PASSWORD' -i -X OPTIONS https://$MY_DAV_SERVER
```

Apache HTTPS response:
```
HTTP/1.1 200 OK
Date: Thu, 21 Jun 2018 12:59:16 GMT
Server: Apache/2.4.18 (Ubuntu)
Allow: GET,HEAD,POST,OPTIONS
Content-Length: 0
Content-Type: text/html
```

**Comment by MrVine** [comment]
@chripo , as you see `Apache HTTPS Server` does not return `DAV` header, so I think it should not be required to successfully `c.connect()`. What do you think?

**Comment by chripo** [comment]
thanks for testing and reporting!!!

**Comment by MrVine** [comment]
@chripo , referenced to your commit I have a question: "Do we need to have `Client.Connect()` method at all?"
If we need this method I offer to remove only `DAV` header's check by replacing this code of `Client.Connect()` method:

```Go
if rs.StatusCode != 200 || (rs.Header.Get("Dav") == "" && rs.Header.Get("DAV") == "") {
	return newPathError("Connect", c.root, rs.StatusCode)
}
```

to this code:

```Go
if rs.StatusCode != 200 {
	return newPathError("Connect", c.root, rs.StatusCode)
}
```

**Comment by chripo** [comment]
yes we could do this as well. but it's one extra call which is more or less useless, because the further call will fail if the server dosen't knows about `dav` or will succeed on regular HTTP methods.

**Comment by MrVine** [comment]
so, we are able to remove `c.Connect()` at all?

**Comment by chripo** [comment]
No, i wouldn't remove the code. Because the project consists of two parts. A library to build a custom client, in your own application and a command, a simple prebuild client or a kind of reference implementation of the lib. The latter one use the library or a subset of methods for his needs.
Hopefully youren't confused.
Thank you very much for your contribution!

**Comment by MrVine** [comment]
Ok, I understand your position and I agree with you :)
Thank you too, @chripo !
