### ISSUE TITLE
nil pointer exception in req() method

### ISSUE THREAD

**Issue by MrVine** [studio-b12/gowebdav#25]
# Software
OS: Windows 10 x64
GO: go1.9.2 windows/amd64
gowebdav: latest version from `master`

# go env
```
set GOARCH=386
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\Go\
set GORACE=
set GOROOT=D:\Programs\Go
set GOTOOLDIR=D:\Programs\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set GO386=sse2
set CC=gcc
set GOGCCFLAGS=-m32 -fmessage-length=0 -fdebug-prefix-map=C:\Users\PC\AppData\Local\Temp\go-build886287271=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=0
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
```

# Issue description
We use `http.Do()` method inside `c.req()`, and do not check for errors returned. So, it is possible to receive `nil` response, and got `nil pointer dereference panic` in line 42. 
`http.Do()` method will return non-nil `error` in following cases:
1. Request is nil
2. Response missing Location header
3. Client failed to parse Location header
4. Method "request.GetBody()" returns error
5. Http.Client.Send() returns error
6. Client timeout was exceeded
In all cases except of (5) this method returns `nil` as a poiner to `http.Response`, which will force app to panic later.

# Conclusion
Taking into account the above mentioned, we need to perform error-checking for `http.Do()` method results.

**Comment by chripo** [comment]
Yes. It got lost.

You are a contributer and you have permission to write/push too. Don't open issues. Use this time an push your fix, even if you're not 100% shure, all things improveable!
Don't be shy. Go on.
Thanks for your report.

**Comment by chripo** [comment]
Just try to avoid merge commits. :grinning:

**Comment by MrVine** [comment]
@chripo, ok, thanks 😄
