### ISSUE TITLE
gowebdav library should not hush up errors

### ISSUE THREAD

**Issue by MrVine** [studio-b12/gowebdav#28]
If we carefully see on following methods:
* `client.mkcol()`, `client.Mkdir()`, `client.MkdirAll()`
* `client.copymove()`, `client.doCopyMove()`
* `client.Write()` and `client.WriteStream()` 
- it suppress real `error`s and returns only status code in the best case.

I propose to change this behaviour to allow user of our library to get original error message.

**Comment by chripo** [comment]
the lower case methods are not going to be exported.
therefore error handling / result handling by status code is simpler.
surely there is space for improvement and consistency, in uppercase methods too!
maybe we should introduce an own error structure that includes the status code, without or with the origin error.
simplicity first. ;)

**Comment by MrVine** [comment]
I have experience of using `gowebdav` with WebDav server which had outdated certificate, and it was difficult for me to answer the question "why my application does not recieves/sends data?", because all what I got back from `gowebdav` was:

```sh
Mkdir /path/to/my/file.txt 400
```

When I fix error suppressing and got this error:
```sh
x509: certificate signed by unknown authority
```
I understand where the problem is and fix it quickly.

That is why I propose to return error messages even from lower case methods.
`Mkdir 400` it is not an good answer, users should knows how the real error sounds to be able to quickly fix it.

**Comment by chripo** [comment]
Indeed.

Maybe we should wrap error and status code for all exported methods.

**Comment by chripo** [comment]
finally done.
thanks to @fischor and @zekroTJA
