### ISSUE TITLE
ReadDir omits returning the first result if it is a directory

### ISSUE THREAD

**Issue by jv512049** [studio-b12/gowebdav#39]
Hello Collaborators,

I am reading a directory using ReadDir API. The contents of the directory are two directories. ReadDir only returns the second directory. 

I debugged the code, and the culprit is the following block of code in client.go file

		if skipSelf {
			skipSelf = false
			if p := getProps(r, "200"); p != nil && p.Type.Local == "collection" {
				r.Props = nil
				return nil
			}
			return newPathError("ReadDir", path, 405)
		}

If I comment out this code, it works as expected. I do not know what this skipSelf thingy is. It does not seem to have it there be necessary when I used it 

**Software**
 - OS: Windows 10
 - Golang: 
 - Version: 1.15

**To Reproduce**
1. ReadDir on a folder that has two folders (no files)
2. You will the second folder in the result

**Expected**
ReadDir should return both dirs.

**Additional context**
My test file: main.go - you need to add your WebDav Url and username/password.

package main

import (
	"log"
	"path/filepath"

	"github.com/studio-b12/gowebdav"
)

func main() {
	root := "xxxx"
	user := "yyyy"
	password := "zzzz"

	c := gowebdav.NewClient(root, user, password)
	err := c.Connect()
	if err != nil {
		log.Fatalf("could not connect %v\n", err)
	}

	readDir(c, "/")
}

func readDir(c *gowebdav.Client, dpath string) {
	fi, err := c.ReadDir(dpath)
	if err != nil {
		log.Fatalf("could not read dir %v\n", err)
	}
	for _, file := range fi {
		if file.IsDir() {
			d := filepath.ToSlash(filepath.Join(dpath, file.Name()))
			log.Printf("Directory: %v\n", d)
			readDir(c, d)
			continue
		}
		log.Printf("File: %v\n", file.Name())
	}
}

**Comment by chripo** [comment]
thank you for your report.

the `skipself` thing skips over the root entry, because the response includes the requested directory itself.
And `ReadDir` method  should list its content, the child entries, therefore we skip the first element.

we ship a [reference implementation](../blob/master/cmd/gowebdav/main.go), but without a recursive listing.

which server you're using?
