### ISSUE TITLE
Error on Folders with '+'

### ISSUE THREAD

**Issue by needsaholiday** [studio-b12/gowebdav#40]
Hello Collaborators,

**Describe the bug**

When we want to Propfind a folder which contains folders with "+", the call fails. Due to the QueryUnescape at
https://github.com/studio-b12/gowebdav/blob/master/client.go#L141
the "+" results in a wrong foldername. in this case "lost+found" becomes "lost found".

Not sure what the purpose of QueryUnescape is, but once we remove it, it works just fine.

**Software**
 - OS: linux
 - Golang: 1.15
 - Version: latest master

**To Reproduce**
1. Create a folder 'lost+found' in a folder 'a'
2. Propfind folder 'a'
3. Propfind returns 'lost found' as the folder name

**Expected**
Expected the folder name "lost+found" to stay that way

**Comment by chuckwagoncomputing** [comment]
I think the real fix here is to use PathUnescape instead of QueryUnescape. It treats '+' properly.

**Comment by chripo** [comment]
+1
thank you.

**Comment by needsaholiday** [comment]
@chuckwagoncomputing true story. Thank you. Applied it to the pull request #41
