### ISSUE TITLE
[err:WriteStream] file write problem: err:WriteStream

### ISSUE THREAD

**Issue by cffycls** [studio-b12/gowebdav#60]
Hello Collaborators,

**Describe the bug**
A short description of what you think the bug is.

**Software**
 - OS: win 11
 - Golang: 1.18.1
 - Version: 8

**To Reproduce**

**Expected**
A short description of what you expected to happen.
```
err:WriteStream xx: 500
```
**Additional context**
```
server is on WSL2 of docker, images is derkades/webdav.
I try to upload a image file
```
![dav_error](https://user-images.githubusercontent.com/29082840/187121053-240ea0d3-6f80-43ad-9292-f6529225b339.png)

**Comment by chripo** [comment]
Thank you for your bug report.
A status code `>=500` means this is a server error.
Can you provide some server logs?

**Comment by chripo** [comment]
if it's still an issue, feel free to reopen.
