### ISSUE TITLE
Authentication fails when deployed to Windows machine without Go installed

### ISSUE THREAD

**Issue by Hajus** [studio-b12/gowebdav#66]
I wrote an app on Windows using basic authentication, which appears as **Go-http-client/2.0** on the server, if run from my developer machine with Go installed, and works well.

On a different machine without Go installed (or on my machine after uninstalling Go) the same client appears as **Microsoft-WebDAV-MiniRedir/10.0.16299** on the server, and authentication fails.

I read quite a bit about dynamic linking if using the net package, but right now I am stuck.

**Comment by chripo** [comment]
can you share some build information?
do you cross compile?

**Comment by chripo** [comment]
Is this still an issues?

**Comment by Hajus** [comment]
I haven't solved the problem, but it's not an issue for me anymore. I run the WebDAV connection on OS level and use simple file copy for my tool.
