### ISSUE TITLE
This is a library usage question，about ContentType.

### ISSUE THREAD

**Issue by xinjiajuan** [studio-b12/gowebdav#67]
I saw that the Type File Struct has a field of ContentType that can be used, but this is just a struct and cannot get the ContentType of the file. Maybe I'm not very familiar with golang and would like to ask how to get it?
```
type File struct {
	path        string
	name        string
	contentType string
	size        int64
	modified    time.Time
	etag        string
	isdir       bool
}

func (f File) ContentType() string {
	return f.contentType
}
```

**Comment by chripo** [comment]
You need to cast the `os.FileInfo` into our `File` structure.
```go
info, error := client.Stat('/file.txt')
...
if file, ok := info.(File); ok {
    fmt.Println(file.ContentType())
}
```
