### ISSUE TITLE
[BUG/FEATURE] OneDrive Support

### ISSUE THREAD

**Issue by Gamer92000** [studio-b12/gowebdav#68]
Hello Collaborators,

**Describe the bug**
When using OneDrive as the WebDav server things get weird. In short: The authentication fails because of Microsoft.

**Software**
 - OS: Linux (Docker)
 - Golang: 1.19.4
 - Version: 60ec5ad560124272abec0b904f79c913c3cb347c

**To Reproduce**
1. Create a client using OneDrive credentials
2. Try to use any (authenticated) request (e.g. `ReadDir()`)
3. Response is empty / unexpected (e.g. no files)

**Expected**
At least an authentication error should be returned. Even better would be support for MS's need to be proprietary.

**Additional context**
Microsoft (as expected) does not follow industry standards and instead of returning `401` on unauthenticated requests they return `302` to redirect you to the login page. The login page then return a `200` status so the webdav client thinks it is a valid result for the original request. On its own this would not be too bad as you could catch the redirect and handle it like a `401`. But since Microsoft use their own authentication method ([MS-PASS](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-pass/2c80637d-438c-4d4b-adc5-903170a779f3) with `Passport1.4`) you also need a new authenticator.

**Comment by bai-jie** [comment]
Related information:
-   Rclone's WebDav implementation of OneDrive: https://github.com/rclone/rclone/blob/v1.61.1/backend/webdav/webdav.go#L559
-   Rclone's WebDav document about OneDrive: https://rclone.org/webdav/#sharepoint-online

Current workaround:
-   set cookie with interceptor: https://github.com/alist-org/alist/blob/v3.9.2/drivers/webdav/util.go#L18-L28
-   and refresh cookies every 12 hours: https://github.com/alist-org/alist/blob/v3.9.2/drivers/webdav/driver.go#L33-L39

**Comment by Gamer92000** [comment]
Thanks for all the references @bai-jie!
Unfortunately, this does not work for OneDrive but only SharePoint. But it still helped a lot with getting me started.
In the end, I mostly followed MS's example for Passport1.4 though.

**Comment by chripo** [comment]
if I´d not get it wrong. we could check for a redirect  or compare the `request` and `response` with the `path` in `Veriify` of `nullAuth` then do the partner server auth to obtain the credentials. we could move the code into the `Authorize` block and make a kind of preflight request. everything should happen in the `nullAuth` which is going to be replaced by a real authenticator.
