### ISSUE TITLE
Digest auth usage

### ISSUE THREAD

**Issue by tejaswinibussety** [studio-b12/gowebdav#72]
Hello Collaborators,

From the docs I see there is a support to use DigestAuth, but I couldn't find how exactly am I supposed to pass the credentials for using Digest Auth, I see by default gowebdav uses basic auth. How can I explicitly ask it to use digest auth? Could you provide an example on how to use DigestAuth with gowebdav client?

**Software**
 - OS: Mac
 - Golang:
```
go version
go version go1.17.1 darwin/amd64
```
 - Version:
```	
github.com/studio-b12/gowebdav v0.0.0-20230203202212-3282f94193f2
```

**Additional context**
I'm trying to upload my HLS content to AWS Elemental MediaPackager

**Comment by chripo** [comment]
The `master` branch has the `Basic` and `Digest` Auth burned into the `c := NewClient(*root, *user, *password)`.
After merging #71 you'll have much more control over the setup.
We're close to bring this into `master`.
Thanks for your patience.

**Comment by chripo** [comment]
Now you can go with `DigestAuth` only by
```go
d:= &DigestAuth{user: "user", pw: "password"}
a:= NewPreemptiveAuth(d)
c:= NewAuthClient("<ROOT>", a)
c.Connect() 
```
